server:
  port: 80

spring:
  application:
    name: cloud-order-openFeign-hystrix-service
# Eureka Client配置
eureka:
  client:
    register-with-eureka: true # 表示向注册中心注册自己,默认为true
    fetch-registry: true # 是否从eurekaServer抓取已有的注册信息
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true

# 设置Feign客户端超时时间(OpenFeign默认支持Ribbon)
ribbon:
  ReadTimeout: 5000 # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ConnectTimeout: 5000 # 指的是建立连接后从服务器读取到可用资源所用的时间
logging:
  level:
    # Feign日志以什么级别监控哪个接口
    com.atguigu.springcloud.serivce.PaymentFeignService: debug

# 设置OpenFeign支持Hystrix
feign:
  hystrix:
    enabled: true
