server:
  port: 9100

spring:
  application:
    name: cloud-gateway-9100
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能,利用微服务名称进行路由
      routes:
        - id: payment_routh # 路由ID,没有固定规则,建议配合服务名
          uri: http://127.0.0.1:8001 # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** # 断言,路径相匹配的进行路由

        - id: payment_routh2
          uri: http://127.0.0.1:8001
          predicates:
            - Path=/payment/discovery

        # 动态路由
        - id: payment_routh3
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/serverPort # 断言,路径相匹配的进行路由
#            - After=2020-04-10T09:03:05.372+08:00[Asia/Shanghai] # 某个时间点之后
#            - before=2020-04-10T09:03:05.372+08:00[Asia/Shanghai] # 某个时间点之前
#            - between=2020-04-09T09:03:05.372+08:00[Asia/Shanghai],2020-04-11T09:03:05.372+08:00[Asia/Shanghai] # 在时间范围之内
#            - Cookie=username,tom
#            - Header=X-Request-Id, \d+ # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.atguigu.com
#            - Method=GET # 请求方法必须是Get请求才能路由
#            - Query=username, \d+ # 要有参数名username并且值还要是整数才能路由
eureka:
  client:
    register-with-eureka: true # 表示向注册中心注册自己,默认为true
    fetch-registry: true # 是否从eurekaServer抓取已有的注册信息
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: gateway9100
    prefer-ip-address: true # 访问路径可以显示IP