server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true # 表示向注册中心注册自己,默认为true
    fetch-registry: true # 是否从eurekaServer抓取已有的注册信息
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true